// Command spindle-bones takes a dance written as joint positions, measures it,
// mends it and writes it into the program.
//
//	go run ./cmd/spindle-bones
//	go run ./cmd/spindle-bones -show bounce -tall 96
//	go run ./cmd/spindle-bones -show bounce -tall 56 -between 3
//
// The drawings for a dance used to be pictures on a sheet, and the sheet had to
// be cut up. Measured on the seven that came first, the figure wandered half a
// cell between one frame and the next — so his head jumped about while he
// danced, and no amount of cutting could put it back. A move written as numbers
// has nothing to align.
//
// What is checked here is the one thing numbers can get wrong that a drawing
// cannot: a hand writing coordinates will quietly stretch a leg to reach a pose.
// So every bone is measured across the whole move and any joint that disagrees
// is pulled back along its own direction onto the length the rest of the move
// keeps. On the first move that arrived, nine bones in ten were already exact
// and the knees strayed by a percent and a half.
//
// What ships is the numbers, not dots: a move is twelve kilobytes of JSON
// against four hundred of baked pictures, and it is drawn at whatever size the
// room turns out to be.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pottom/spindle/internal/ui/bones"
)

const (
	assets = "assets/moves"
	out    = "internal/ui/bones_gen.go"
)

func main() {
	show := flag.String("show", "", "draw this move in the terminal")
	tall := flag.Int("tall", 60, "with -show, how tall to draw him, in dots")
	between := flag.Int("between", 0, "with -show, how many frames to work out between each pair of keyframes")
	flag.Parse()

	found, err := filepath.Glob(filepath.Join(assets, "*", "*.json"))
	if err != nil {
		fail(err)
	}
	sort.Strings(found)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/spindle-bones. DO NOT EDIT.\n\npackage ui\n\n")
	fmt.Fprintf(&b, "import \"github.com/pottom/spindle/internal/ui/bones\"\n\n")
	fmt.Fprintf(&b, "// The dances, written as joint positions outside this repository and mended\n")
	fmt.Fprintf(&b, "// here. See cmd/spindle-bones, docs/MOVES.md, and the licence beside each set.\n\n")
	fmt.Fprintf(&b, "var boneDances = map[string]bones.Dance{\n")

	var wrote int
	for _, path := range found {
		if filepath.Base(path) == "move.json" {
			continue // the raster manifest, which is a different thing
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			fail(err)
		}
		d, err := bones.Read(raw)
		if err != nil {
			fail(fmt.Errorf("%s: %w", path, err))
		}
		if d.Move == "" || len(d.Frames) < 2 {
			fail(fmt.Errorf("%s: a move wants a name and at least two frames", path))
		}

		say(d)
		mended := d.Mend()
		fmt.Printf("  %d joints pulled back onto their bone\n\n", mended)

		emit(&b, d)
		wrote++

		if *show == d.Move {
			defer draw(d, *tall, *between)
		}
	}
	fmt.Fprintf(&b, "}\n")

	if wrote == 0 {
		fmt.Println("no moves written as numbers yet")
		return
	}
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fail(fmt.Errorf("format: %w", err))
	}
	if err := os.WriteFile(out, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d bytes, %d moves)\n", out, len(src), wrote)
}

// say measures the move before anything is done to it.
func say(d bones.Dance) {
	fmt.Printf("%s: %d keyframes\n", d.Move, len(d.Frames))
	for _, b := range bones.Bones() {
		want, stray := d.Length(b)
		flag := ""
		if stray > 0.05 {
			flag = "  <-- the bone changes length"
		}
		fmt.Printf("  %-14s %7.1f  strays %4.1f%%%s\n", b.Name, want, stray*100, flag)
	}

	// And how far anything moves between one keyframe and the next, including
	// across the join: a loop whose join costs more than a step is not a loop.
	var step, join float64
	for i := range d.Frames {
		at := worst(d.Frames[i], d.Frames[(i+1)%len(d.Frames)])
		if i == len(d.Frames)-1 {
			join = at
			continue
		}
		step = math.Max(step, at)
	}
	fmt.Printf("  the furthest a joint travels between keyframes is %.0f, and across the loop %.0f\n", step, join)
}

func worst(a, b bones.Pose) float64 {
	var at float64
	for _, bone := range bones.Bones() {
		for _, p := range [][2]*bones.Point{
			{bone.From(&a), bone.From(&b)},
			{bone.To(&a), bone.To(&b)},
		} {
			at = math.Max(at, bones.Span(*p[0], *p[1]))
		}
	}
	return at
}

func emit(b *strings.Builder, d bones.Dance) {
	fmt.Fprintf(b, "\t%q: {Move: %q, Box: %g, Floor: %g, Frames: []bones.Pose{\n", d.Move, d.Move, d.Box, d.Floor)
	for _, f := range d.Frames {
		fmt.Fprintf(b, "\t\t{Head: %s, Neck: %s, Hip: %s, ElbowL: %s, HandL: %s, ElbowR: %s, HandR: %s, KneeL: %s, FootL: %s, KneeR: %s, FootR: %s},\n",
			point(f.Head), point(f.Neck), point(f.Hip), point(f.ElbowL), point(f.HandL),
			point(f.ElbowR), point(f.HandR), point(f.KneeL), point(f.FootL), point(f.KneeR), point(f.FootR))
	}
	fmt.Fprintf(b, "\t}},\n")
}

func point(p bones.Point) string {
	if p.R != 0 {
		return fmt.Sprintf("bones.Point{X: %.1f, Y: %.1f, R: %.1f}", p.X, p.Y, p.R)
	}
	return fmt.Sprintf("bones.Point{X: %.1f, Y: %.1f}", p.X, p.Y)
}

// draw puts the move in the terminal, in braille, the way the screen will.
func draw(d bones.Dance, tall, between int) {
	left, right, top := d.Reach()
	scale := float64(tall) / (d.Floor - top)
	wide := int((right-left)*scale) + 2
	pen := bones.Pen(tall)

	steps := len(d.Frames) * (between + 1)
	const across = 6
	for at := 0; at < steps; at += across {
		end := min(at+across, steps)

		w, h := (wide+4)*(end-at), tall+4
		lit := make([]bool, w*h)
		for i := at; i < end; i++ {
			frame := float64(i) / float64(between+1)
			bones.Draw(d.At(frame), d.Box, d.Floor, scale,
				(i-at)*(wide+4)-int(left*scale)+1, tall+2, pen, func(x, y int) {
					if x >= 0 && y >= 0 && x < w && y < h {
						lit[y*w+x] = true
					}
				})
		}

		fmt.Printf("\n  frames %d-%d\n", at, end-1)
		for y := 0; y < h; y += 4 {
			var line strings.Builder
			for x := 0; x < w; x += 2 {
				var bits rune
				for _, b := range [][3]int{{0, 0, 0}, {0, 1, 1}, {0, 2, 2}, {1, 0, 3}, {1, 1, 4}, {1, 2, 5}, {0, 3, 6}, {1, 3, 7}} {
					if px, py := x+b[0], y+b[1]; px < w && py < h && lit[py*w+px] {
						bits |= 1 << b[2]
					}
				}
				line.WriteRune(0x2800 + bits)
			}
			fmt.Println("  " + line.String())
		}
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "spindle-bones:", err)
	os.Exit(1)
}
