// Command spindle-marks turns drawings into the marks a bar of music is set in.
//
// A bar nobody sings puts up a row of marks, and until now they were ♪ and ♫,
// set from the same face the lyrics are. Every one of them already rides its own
// slice of the spectrum — the bass at the left, the cymbals at the right — so
// the row is a map of the sound that says nothing about it. Made of instruments
// it says it: a kick at the left jumping on the kick, a cymbal at the right
// jumping on the cymbals.
//
// Run it when a mark is added or a manifest changes:
//
//	go run ./cmd/spindle-marks
//
// It reads every assets/marks/*/mark.json and writes one generated Go file into
// internal/ui. Nothing here runs at playback time; what ships is the dots.
//
// # Why drawings and not a font
//
// The face the lyrics are set in carries ♪ and ♫ and nothing else musical —
// measured, its whole inventory is essentially CP437, with no ♬, no ♩, no
// instruments and no weather. A Nerd Font would carry thousands of icons and
// render cleanly at this size, and it would mean shipping a megabyte of font to
// use eight of them.
//
// The deciding reason is not the inventory, though. It is the stroke. Every
// other picture on that screen is a stroke two or three dots wide — the type,
// the meters, the water — and an outline drawn as SVG has its stroke width set
// here, per baked size, so a mark comes out the same weight at 24 dots and at
// 72. A font's stroke scales with the glyph: invisible at the small end, fat at
// the large one.
//
// # Why these drawings
//
// Tabler Icons are true strokes — stroke-width on a 24 unit grid — where
// Phosphor and Font Awesome are filled paths, and a filled shape among strokes
// reads as a hole punched in the picture. Two things about the files have to be
// dealt with before they will parse: the comment at the top of each one, and
// stroke="currentColor", which the rasteriser cannot resolve. Both are done
// where the assets are prepared rather than here, so what is committed is what
// is drawn.
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/srwiley/oksvg"
	"github.com/srwiley/rasterx"
)

// set is a manifest: the drawings, in the order they stand in the row, and the
// sizes they are baked at.
type set struct {
	Name    string   `json:"name"`
	From    string   `json:"from"`
	Licence string   `json:"licence"`
	Marks   []string `json:"marks"`
	Heights []height `json:"heights"`

	// Faces turns the row in on itself: with it set, everything past the middle
	// is drawn the other way round, so the two halves look at each other rather
	// than all one way. A row of people all facing the same direction is a queue;
	// facing each other, it is a group. Drawings with no side to them — a face,
	// a piano — do not care either way, which is why this is a property of the
	// set rather than of each drawing.
	Faces string `json:"faces"`
}

// height is one size a mark is baked at: how tall, and how wide its stroke
// comes out in dots.
type height struct {
	Tall  int `json:"tall"`
	Thick int `json:"thick"`
}

const (
	assets = "assets/marks"
	out    = "internal/ui/marks_gen.go"

	// over is how many times each dot is drawn over before it is thresholded.
	//
	// Four. A three dot stroke is a thin thing, and rasterised straight onto the
	// dot grid its edges land near the threshold all along it — which comes out
	// as a dashed line rather than a stroke. Supersampled, every dot gets a real
	// coverage figure and the line holds together.
	over = 4

	// lit is how much of a dot has to be covered for it to be set. Half, which
	// is the same edge the type is taken at.
	lit = 128
)

func main() {
	show := flag.String("show", "", "after baking, draw these sets in the terminal — a name, several separated by commas, or \"all\"")
	only := flag.Int("size", 0, "with -show, draw only this baked height in dots")
	into := flag.String("png", "", "with -show, also write the rows to this file as a picture, blown up to look at")
	flag.Parse()

	paths, err := filepath.Glob(filepath.Join(assets, "*", "mark.json"))
	if err != nil || len(paths) == 0 {
		fail(fmt.Errorf("no marks under %s", assets))
	}
	sort.Strings(paths)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/spindle-marks. DO NOT EDIT.\n\npackage ui\n\n")
	fmt.Fprintf(&b, "// The marks a bar of music is set in, drawn rather than set from a face.\n")
	fmt.Fprintf(&b, "// See cmd/spindle-marks, and the licence beside each set's drawings.\n\n")
	fmt.Fprintf(&b, "var markSets = map[string]markSet{\n")

	for _, path := range paths {
		s, err := read(path)
		if err != nil {
			fail(err)
		}
		if err := emit(&b, filepath.Dir(path), s); err != nil {
			fail(err)
		}
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fail(fmt.Errorf("format: %w", err))
	}
	if err := os.WriteFile(out, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", out, len(src))

	if *show != "" {
		draw(paths, *show, *only, *into)
	}
}

// draw prints the baked marks in the terminal, in the dots they will be drawn
// in and nothing else.
//
// It is here rather than in a test because of what it is for. A drawing is
// judged at the size it is seen at, and the size it is seen at is usually the
// smallest one baked — a sheet that is beautiful at 300 pixels can be a scatter
// of dots at 24, and that has now happened twice. Every other way of finding
// out involves opening a picture in something, which is a step nobody takes
// while they are still deciding.
//
// Braille, because that is what the screen draws in: two dots across and four
// down in every cell, so what comes out here is exactly what goes up there.
func draw(paths []string, want string, only int, into string) {
	var shot []row
	var found bool
	for _, path := range paths {
		s, err := read(path)
		if err != nil {
			fail(err)
		}
		if !wanted(want, s.Name) {
			continue
		}
		found = true
		dir := filepath.Dir(path)
		for _, h := range s.Heights {
			if only > 0 && h.Tall != only {
				continue
			}
			var row []dots
			for i, name := range s.Marks {
				turn := s.Faces == "in" && float64(i) > float64(len(s.Marks)-1)/2
				m, err := convert(filepath.Join(dir, name), h, turn)
				if err != nil {
					fail(err)
				}
				row = append(row, m)
			}
			// What the row costs across the screen, which is the number that
			// decides which size it is drawn at: the largest that holds all of
			// it wins, so a wide set is a small set. See markRowFor.
			var wide int
			for _, m := range row {
				wide += m.wide
			}
			gap := int(0.45 * float64(h.Tall)) // markSpread
			across := wide + gap*(len(row)-1)
			fmt.Printf("\n%s at %d dots, pen %d — %d marks, %.2f wide each, row %d dots = %d cells\n",
				s.Name, h.Tall, h.Thick, len(row),
				float64(wide)/float64(len(row))/float64(h.Tall), across, (across+1)/2)
			// Which of them is the wide one, since one mark out of eight is
			// enough to cost the row a size.
			if only > 0 {
				for i, m := range row {
					fmt.Printf("  %-12s %.2f wide\n", strings.TrimSuffix(s.Marks[i], filepath.Ext(s.Marks[i])),
						float64(m.wide)/float64(h.Tall))
				}
			}
			for _, line := range braille(row) {
				fmt.Println(line)
			}
			shot = append(shot, rowOf(s.Name, h.Tall, row))
		}
	}
	if into != "" && len(shot) > 0 {
		if err := picture(into, shot); err != nil {
			fail(err)
		}
		fmt.Printf("\nwrote %s\n", into)
	}
	if !found {
		// A tool that answers nothing is a tool that has been misread. There is
		// no set by that name, and saying so beats printing an empty screen.
		var names []string
		for _, path := range paths {
			if s, err := read(path); err == nil {
				names = append(names, s.Name)
			}
		}
		fmt.Fprintf(os.Stderr, "spindle-marks: no set called %q. There is %s.\n",
			want, strings.Join(names, ", "))
		os.Exit(1)
	}
}

// wanted reports whether a set was asked for: all of them, one of them, or one
// of a list — so two ways of drawing the same row can be put on the screen one
// under the other and told apart by eye, which is the only way this is decided.
func wanted(want, name string) bool {
	if want == "all" {
		return true
	}
	for _, one := range strings.Split(want, ",") {
		if strings.TrimSpace(one) == name {
			return true
		}
	}
	return false
}

// row is one baked size of one set, kept for the picture.
type row struct {
	name string
	tall int
	of   []dots
}

func rowOf(name string, tall int, of []dots) row { return row{name, tall, of} }

// picture writes the rows out blown up, because a dot is judged by eye and the
// eye wants it larger than a terminal cell.
func picture(path string, rows []row) error {
	const zoom, gap = 8, 6
	var wide, tall int
	for _, r := range rows {
		w := 0
		for _, m := range r.of {
			w += m.wide + gap
		}
		wide = max(wide, w)
		tall += r.tall + gap*2
	}
	img := image.NewGray(image.Rect(0, 0, wide*zoom, tall*zoom))
	y0 := gap
	for _, r := range rows {
		x0 := gap
		for _, m := range r.of {
			raw, err := base64.StdEncoding.DecodeString(m.bits)
			if err != nil {
				return err
			}
			for y := range m.tall {
				for x := range m.wide {
					i := y*m.wide + x
					if i/8 >= len(raw) || raw[i/8]&(1<<(i%8)) == 0 {
						continue
					}
					for zy := range zoom {
						for zx := range zoom {
							img.SetGray((x0+x)*zoom+zx, (y0+y+r.tall-m.tall)*zoom+zy, color.Gray{Y: 255})
						}
					}
				}
			}
			x0 += m.wide + gap
		}
		y0 += r.tall + gap*2
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return png.Encode(f, img)
}

// braille lays a row of drawings out side by side in braille cells.
func braille(row []dots) []string {
	var tall int
	for _, m := range row {
		tall = max(tall, m.tall)
	}
	rows := (tall + dotsPerCellY - 1) / dotsPerCellY

	// The dot each bit of a braille cell stands for, which is not the order the
	// cell is written in: the eighth and seventh dots are the bottom row, added
	// to the six of the original.
	bit := [dotsPerCellX][dotsPerCellY]uint8{{0, 1, 2, 6}, {3, 4, 5, 7}}

	out := make([]string, rows)
	for _, m := range row {
		raw, err := base64.StdEncoding.DecodeString(m.bits)
		if err != nil {
			fail(err)
		}
		on := func(x, y int) bool {
			if x < 0 || y < 0 || x >= m.wide || y >= m.tall {
				return false
			}
			i := y*m.wide + x
			return i/8 < len(raw) && raw[i/8]&(1<<(i%8)) != 0
		}
		// Sat on the floor, so a row of them stands on one line.
		lift := tall - m.tall
		for r := range rows {
			var b strings.Builder
			for x := 0; x < m.wide; x += dotsPerCellX {
				var cell rune
				for dx := range dotsPerCellX {
					for dy := range dotsPerCellY {
						if on(x+dx, r*dotsPerCellY+dy-lift) {
							cell |= 1 << bit[dx][dy]
						}
					}
				}
				b.WriteRune(0x2800 + cell)
			}
			out[r] += b.String() + "  "
		}
	}
	return out
}

const (
	dotsPerCellX = 2
	dotsPerCellY = 4
)

func read(path string) (set, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return set{}, err
	}
	var s set
	if err := json.Unmarshal(raw, &s); err != nil {
		return set{}, fmt.Errorf("%s: %w", path, err)
	}
	if s.Name == "" || len(s.Marks) == 0 || len(s.Heights) == 0 {
		return set{}, fmt.Errorf("%s: a set wants a name, a mark and a height", path)
	}
	return s, nil
}

func emit(b *strings.Builder, dir string, s set) error {
	fmt.Fprintf(b, "\t%q: {\n\t\tfrom: %q,\n\t\tlicence: %q,\n\t\tsizes: []markSize{\n", s.Name, s.From, s.Licence)

	for _, h := range s.Heights {
		fmt.Fprintf(b, "\t\t\t{tall: %d, marks: []markDots{\n", h.Tall)
		for i, name := range s.Marks {
			// Past the middle they turn back on the row. The middle one of an
			// odd row is left alone: it is the one everybody else is facing.
			turn := s.Faces == "in" && float64(i) > float64(len(s.Marks)-1)/2

			m, err := convert(filepath.Join(dir, name), h, turn)
			if err != nil {
				return err
			}
			fmt.Fprintf(b, "\t\t\t\t{name: %q, wide: %d, tall: %d, bits: %q},\n",
				strings.TrimSuffix(name, filepath.Ext(name)), m.wide, m.tall, m.bits)
		}
		fmt.Fprintf(b, "\t\t\t}},\n")
	}
	fmt.Fprintf(b, "\t\t},\n\t},\n")
	return nil
}

// dots is one drawing at one size.
type dots struct {
	wide, tall int
	bits       string
}

var strokeWidth = regexp.MustCompile(`stroke-width="[^"]*"`)

// convert takes one drawing to dots at one height.
//
// The stroke is rewritten before anything is drawn, and that one line is the
// whole argument for drawings over a font: it is set here, per size, so a mark
// comes out the same weight however large it is drawn.
//
// What it is set to is not what the grid would suggest, and it was measured
// rather than reasoned. The rasteriser scales the *geometry* to the target and
// leaves the stroke in the target's own pixels: the same width of 3 covered 23%
// of a 54 pixel target and 4% of a 216 pixel one. So the width to ask for is
// simply the stroke wanted, in dots, times the supersampling — after the
// averaging that is exactly thick dots, at every size.
func convert(path string, h height, turn bool) (dots, error) {
	if strings.EqualFold(filepath.Ext(path), ".png") {
		return trace(path, h, turn)
	}
	return render(path, h, turn)
}

func render(path string, h height, turn bool) (dots, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return dots{}, err
	}
	if bytes.Contains(raw, []byte("currentColor")) {
		return dots{}, fmt.Errorf("%s: stroke is currentColor, which the rasteriser cannot resolve", path)
	}

	raw = strokeWidth.ReplaceAll(raw, []byte(`stroke-width="`+strconv.Itoa(h.Thick*over)+`"`))

	icon, err := oksvg.ReadIconStream(bytes.NewReader(raw))
	if err != nil {
		return dots{}, fmt.Errorf("%s: %w", path, err)
	}

	big := h.Tall * over
	icon.SetTarget(0, 0, float64(big), float64(big))

	rgba := image.NewRGBA(image.Rect(0, 0, big, big))
	icon.Draw(rasterx.NewDasher(big, big, rasterx.NewScannerGV(big, big, rgba, rgba.Bounds())), 1)

	// Averaged down to the dot grid. What is wanted is how much ink covers a
	// dot, whatever colour it was drawn in — and turned over here if the row
	// wants it facing the other way, which is a read of the same drawing rather
	// than a second one to keep.
	grey := image.NewGray(image.Rect(0, 0, h.Tall, h.Tall))
	for y := range h.Tall {
		for x := range h.Tall {
			from := x
			if turn {
				from = h.Tall - 1 - x
			}

			var sum int
			for dy := range over {
				for dx := range over {
					_, _, _, a := rgba.At(from*over+dx, y*over+dy).RGBA()
					sum += int(a >> 8)
				}
			}
			grey.SetGray(x, y, color.Gray{Y: uint8(sum / (over * over))})
		}
	}

	return pack(grey), nil
}

// trace takes a drawing that is already a picture rather than a set of paths.
//
// A drawing made outside this repository does not arrive as strokes, and there
// is nothing to rewrite: what it was drawn with is baked into the pixels. So the
// stroke is measured instead of set — the commonest run of ink across the figure
// is how wide the pen was — and once the picture is down on the dot grid it is
// thickened back up to the weight every other mark on this screen has.
//
// Measured on the row this was written for, whose figures are about 170 pixels
// tall: the pen comes out 6.4 dots at 72, 4.8 at 54, 3.2 at 36 and 2.1 at 24. So
// only the smallest size needs anything, and there it needs it badly — at 2 dots
// the threshold leaves a dashed line, which is the same thing that decided the
// stroke width for the drawn sets.
func trace(path string, h height, turn bool) (dots, error) {
	f, err := os.Open(path)
	if err != nil {
		return dots{}, err
	}
	defer f.Close()

	pic, err := png.Decode(f)
	if err != nil {
		return dots{}, fmt.Errorf("%s: %w", path, err)
	}
	b := pic.Bounds()

	ink := func(x, y int) bool {
		r, g, bl, _ := pic.At(x, y).RGBA()
		return (r+g+bl)/3>>8 >= lit
	}

	// What the picture actually drew. A figure is cut to its own ink so that a
	// row of them stands on one floor whatever the file's margins were.
	left, top, right, bottom := b.Max.X, b.Max.Y, b.Min.X-1, b.Min.Y-1
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			if !ink(x, y) {
				continue
			}
			left, top = min(left, x), min(top, y)
			right, bottom = max(right, x), max(bottom, y)
		}
	}
	if right < left {
		return dots{}, fmt.Errorf("%s: the picture is empty", path)
	}
	fw, fh := right-left+1, bottom-top+1

	// Fitted to the height, and as wide as that leaves it: a mark keeps its own
	// shape, and the row spaces them by what they came out as.
	wide := max(fw*h.Tall/fh, 1)
	on := make([]bool, wide*h.Tall)
	for dy := range h.Tall {
		for dx := range wide {
			from := dx
			if turn {
				from = wide - 1 - dx
			}
			var covered, all int
			for sy := dy * fh / h.Tall; sy < max((dy+1)*fh/h.Tall, dy*fh/h.Tall+1); sy++ {
				for sx := from * fw / wide; sx < max((from+1)*fw/wide, from*fw/wide+1); sx++ {
					all++
					if ink(left+sx, top+sy) {
						covered++
					}
				}
			}
			on[dy*wide+dx] = all > 0 && covered*2 >= all
		}
	}

	// The pen, in dots, and taken to the weight the set asked for — thickened
	// when the size has thinned it away, thinned when the picture was drawn with
	// a heavier hand than this screen draws with. Both matter: a picture carries
	// one pen for every size it is baked at, so without this a row is a hairline
	// at the bottom of the range and a set of clubs at the top.
	pen := float64(penOf(pic, ink, left, right, top, bottom)) * float64(h.Tall) / float64(fh)
	// A dot at a time, and to one side. Grown the obvious way — a ring of eight
	// neighbours — a pen goes 1, 3, 5: there is no even weight to be had, and a
	// set asked for 2 came out at 3 with nothing to show for the asking. Adding
	// a dot below and to the right instead moves it a whole dot at a time, which
	// is the difference between a row that reads and a row of clubs.
	for pen+0.5 < float64(h.Thick) {
		on = fatten(on, wide, h.Tall)
		pen++
	}
	for pen-1 > float64(h.Thick) {
		on = thin(on, wide, h.Tall)
		pen -= 2
	}

	grey := image.NewGray(image.Rect(0, 0, wide, h.Tall))
	for i, set := range on {
		if set {
			grey.SetGray(i%wide, i/wide, color.Gray{Y: 255})
		}
	}
	return pack(grey), nil
}

// penOf is how wide the pen was, in the picture's own pixels: the commonest run
// of ink across it.
func penOf(pic image.Image, ink func(int, int) bool, left, right, top, bottom int) int {
	runs := map[int]int{}
	for y := top; y <= bottom; y++ {
		var n int
		for x := left; x <= right; x++ {
			if ink(x, y) {
				n++
				continue
			}
			if n > 0 {
				runs[n]++
			}
			n = 0
		}
		if n > 0 {
			runs[n]++
		}
	}
	best, most := 1, 0
	for n, count := range runs {
		if count > most || (count == most && n < best) {
			best, most = n, count
		}
	}
	return best
}

// grow thickens by one dot in every direction.
// fatten adds one dot below and to the right of everything set, which takes a
// pen up by exactly one.
func fatten(on []bool, wide, tall int) []bool {
	out := make([]bool, len(on))
	for y := range tall {
		for x := range wide {
			if !on[y*wide+x] {
				continue
			}
			out[y*wide+x] = true
			if x+1 < wide {
				out[y*wide+x+1] = true
			}
			if y+1 < tall {
				out[(y+1)*wide+x] = true
			}
			if x+1 < wide && y+1 < tall {
				out[(y+1)*wide+x+1] = true
			}
		}
	}
	return out
}

// thin takes a dot off every edge, which is grow run backwards.
func thin(on []bool, wide, tall int) []bool {
	out := make([]bool, len(on))
	for y := range tall {
		for x := range wide {
			if !on[y*wide+x] {
				continue
			}
			keep := true
			for dy := -1; dy <= 1 && keep; dy++ {
				for dx := -1; dx <= 1; dx++ {
					ny, nx := y+dy, x+dx
					if ny < 0 || ny >= tall || nx < 0 || nx >= wide || !on[ny*wide+nx] {
						keep = false
						break
					}
				}
			}
			out[y*wide+x] = keep
		}
	}
	return out
}

// pack trims the drawing to what it actually lit and writes the dots out a bit
// each, so a set costs what it draws rather than what it was given.
func pack(g *image.Gray) dots {
	b := g.Bounds()
	left, top, right, bottom := b.Max.X, b.Max.Y, b.Min.X-1, b.Min.Y-1
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			if g.GrayAt(x, y).Y < lit {
				continue
			}
			left, top = min(left, x), min(top, y)
			right, bottom = max(right, x), max(bottom, y)
		}
	}
	if right < left {
		return dots{}
	}

	wide, tall := right-left+1, bottom-top+1
	bits := make([]byte, (wide*tall+7)/8)
	for y := range tall {
		for x := range wide {
			if g.GrayAt(left+x, top+y).Y < lit {
				continue
			}
			at := y*wide + x
			bits[at/8] |= 1 << (at % 8)
		}
	}
	return dots{wide: wide, tall: tall, bits: base64.StdEncoding.EncodeToString(bits)}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "spindle-marks:", err)
	os.Exit(1)
}
