// Command spindle-marks turns drawings into the marks a bar of music is set in.
//
// A bar nobody sings puts up a row of marks, and until now they were ♪ and ♫,
// set from the same face the lyrics are. Every one of them already rides its own
// slice of the spectrum — the bass at the left, the cymbals at the right — so
// the row is a map of the sound that says nothing about it. Made of instruments
// it says it: a kick at the left jumping on the kick, a cymbal at the right
// jumping on the cymbals.
//
// Run it when a mark is added or a manifest changes:
//
//	go run ./cmd/spindle-marks
//
// It reads every assets/marks/*/mark.json and writes one generated Go file into
// internal/ui. Nothing here runs at playback time; what ships is the dots.
//
// # Why drawings and not a font
//
// The face the lyrics are set in carries ♪ and ♫ and nothing else musical —
// measured, its whole inventory is essentially CP437, with no ♬, no ♩, no
// instruments and no weather. A Nerd Font would carry thousands of icons and
// render cleanly at this size, and it would mean shipping a megabyte of font to
// use eight of them.
//
// The deciding reason is not the inventory, though. It is the stroke. Every
// other picture on that screen is a stroke two or three dots wide — the type,
// the meters, the water — and an outline drawn as SVG has its stroke width set
// here, per baked size, so a mark comes out the same weight at 24 dots and at
// 72. A font's stroke scales with the glyph: invisible at the small end, fat at
// the large one.
//
// # Why these drawings
//
// Tabler Icons are true strokes — stroke-width on a 24 unit grid — where
// Phosphor and Font Awesome are filled paths, and a filled shape among strokes
// reads as a hole punched in the picture. Two things about the files have to be
// dealt with before they will parse: the comment at the top of each one, and
// stroke="currentColor", which the rasteriser cannot resolve. Both are done
// where the assets are prepared rather than here, so what is committed is what
// is drawn.
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"go/format"
	"image"
	"image/color"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/srwiley/oksvg"
	"github.com/srwiley/rasterx"
)

// set is a manifest: the drawings, in the order they stand in the row, and the
// sizes they are baked at.
type set struct {
	Name    string   `json:"name"`
	From    string   `json:"from"`
	Licence string   `json:"licence"`
	Marks   []string `json:"marks"`
	Heights []height `json:"heights"`

	// Faces turns the row in on itself: with it set, everything past the middle
	// is drawn the other way round, so the two halves look at each other rather
	// than all one way. A row of people all facing the same direction is a queue;
	// facing each other, it is a group. Drawings with no side to them — a face,
	// a piano — do not care either way, which is why this is a property of the
	// set rather than of each drawing.
	Faces string `json:"faces"`
}

// height is one size a mark is baked at: how tall, and how wide its stroke
// comes out in dots.
type height struct {
	Tall  int `json:"tall"`
	Thick int `json:"thick"`
}

const (
	assets = "assets/marks"
	out    = "internal/ui/marks_gen.go"

	// over is how many times each dot is drawn over before it is thresholded.
	//
	// Four. A three dot stroke is a thin thing, and rasterised straight onto the
	// dot grid its edges land near the threshold all along it — which comes out
	// as a dashed line rather than a stroke. Supersampled, every dot gets a real
	// coverage figure and the line holds together.
	over = 4

	// lit is how much of a dot has to be covered for it to be set. Half, which
	// is the same edge the type is taken at.
	lit = 128
)

func main() {
	paths, err := filepath.Glob(filepath.Join(assets, "*", "mark.json"))
	if err != nil || len(paths) == 0 {
		fail(fmt.Errorf("no marks under %s", assets))
	}
	sort.Strings(paths)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/spindle-marks. DO NOT EDIT.\n\npackage ui\n\n")
	fmt.Fprintf(&b, "// The marks a bar of music is set in, drawn rather than set from a face.\n")
	fmt.Fprintf(&b, "// See cmd/spindle-marks, and the licence beside each set's drawings.\n\n")
	fmt.Fprintf(&b, "var markSets = map[string]markSet{\n")

	for _, path := range paths {
		s, err := read(path)
		if err != nil {
			fail(err)
		}
		if err := emit(&b, filepath.Dir(path), s); err != nil {
			fail(err)
		}
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fail(fmt.Errorf("format: %w", err))
	}
	if err := os.WriteFile(out, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", out, len(src))
}

func read(path string) (set, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return set{}, err
	}
	var s set
	if err := json.Unmarshal(raw, &s); err != nil {
		return set{}, fmt.Errorf("%s: %w", path, err)
	}
	if s.Name == "" || len(s.Marks) == 0 || len(s.Heights) == 0 {
		return set{}, fmt.Errorf("%s: a set wants a name, a mark and a height", path)
	}
	return s, nil
}

func emit(b *strings.Builder, dir string, s set) error {
	fmt.Fprintf(b, "\t%q: {\n\t\tfrom: %q,\n\t\tlicence: %q,\n\t\tsizes: []markSize{\n", s.Name, s.From, s.Licence)

	for _, h := range s.Heights {
		fmt.Fprintf(b, "\t\t\t{tall: %d, marks: []markDots{\n", h.Tall)
		for i, name := range s.Marks {
			// Past the middle they turn back on the row. The middle one of an
			// odd row is left alone: it is the one everybody else is facing.
			turn := s.Faces == "in" && float64(i) > float64(len(s.Marks)-1)/2

			m, err := convert(filepath.Join(dir, name), h, turn)
			if err != nil {
				return err
			}
			fmt.Fprintf(b, "\t\t\t\t{name: %q, wide: %d, tall: %d, bits: %q},\n",
				strings.TrimSuffix(name, filepath.Ext(name)), m.wide, m.tall, m.bits)
		}
		fmt.Fprintf(b, "\t\t\t}},\n")
	}
	fmt.Fprintf(b, "\t\t},\n\t},\n")
	return nil
}

// dots is one drawing at one size.
type dots struct {
	wide, tall int
	bits       string
}

var strokeWidth = regexp.MustCompile(`stroke-width="[^"]*"`)

// convert takes one drawing to dots at one height.
//
// The stroke is rewritten before anything is drawn, and that one line is the
// whole argument for drawings over a font: it is set here, per size, so a mark
// comes out the same weight however large it is drawn.
//
// What it is set to is not what the grid would suggest, and it was measured
// rather than reasoned. The rasteriser scales the *geometry* to the target and
// leaves the stroke in the target's own pixels: the same width of 3 covered 23%
// of a 54 pixel target and 4% of a 216 pixel one. So the width to ask for is
// simply the stroke wanted, in dots, times the supersampling — after the
// averaging that is exactly thick dots, at every size.
func convert(path string, h height, turn bool) (dots, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return dots{}, err
	}
	if bytes.Contains(raw, []byte("currentColor")) {
		return dots{}, fmt.Errorf("%s: stroke is currentColor, which the rasteriser cannot resolve", path)
	}

	raw = strokeWidth.ReplaceAll(raw, []byte(`stroke-width="`+strconv.Itoa(h.Thick*over)+`"`))

	icon, err := oksvg.ReadIconStream(bytes.NewReader(raw))
	if err != nil {
		return dots{}, fmt.Errorf("%s: %w", path, err)
	}

	big := h.Tall * over
	icon.SetTarget(0, 0, float64(big), float64(big))

	rgba := image.NewRGBA(image.Rect(0, 0, big, big))
	icon.Draw(rasterx.NewDasher(big, big, rasterx.NewScannerGV(big, big, rgba, rgba.Bounds())), 1)

	// Averaged down to the dot grid. What is wanted is how much ink covers a
	// dot, whatever colour it was drawn in — and turned over here if the row
	// wants it facing the other way, which is a read of the same drawing rather
	// than a second one to keep.
	grey := image.NewGray(image.Rect(0, 0, h.Tall, h.Tall))
	for y := range h.Tall {
		for x := range h.Tall {
			from := x
			if turn {
				from = h.Tall - 1 - x
			}

			var sum int
			for dy := range over {
				for dx := range over {
					_, _, _, a := rgba.At(from*over+dx, y*over+dy).RGBA()
					sum += int(a >> 8)
				}
			}
			grey.SetGray(x, y, color.Gray{Y: uint8(sum / (over * over))})
		}
	}

	return pack(grey, h.Tall), nil
}

// pack trims the drawing to what it actually lit and writes the dots out a bit
// each, so a set costs what it draws rather than what it was given.
func pack(g *image.Gray, side int) dots {
	left, top, right, bottom := side, side, -1, -1
	for y := range side {
		for x := range side {
			if g.GrayAt(x, y).Y < lit {
				continue
			}
			left, top = min(left, x), min(top, y)
			right, bottom = max(right, x), max(bottom, y)
		}
	}
	if right < 0 {
		return dots{}
	}

	wide, tall := right-left+1, bottom-top+1
	bits := make([]byte, (wide*tall+7)/8)
	for y := range tall {
		for x := range wide {
			if g.GrayAt(left+x, top+y).Y < lit {
				continue
			}
			at := y*wide + x
			bits[at/8] |= 1 << (at % 8)
		}
	}
	return dots{wide: wide, tall: tall, bits: base64.StdEncoding.EncodeToString(bits)}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "spindle-marks:", err)
	os.Exit(1)
}
