// Command spindle-signs bakes the placards the walker carries.
//
//	go run ./cmd/spindle-signs
//
// It reads assets/signs/*.png — one drawing per switch, cut off a sheet by
// cmd/spindle-sheet — and writes internal/ui/signs_gen.go. Nothing here runs at
// playback time; what ships is the dots.
//
// # Why these are not baked at sizes, when everything else is
//
// Marks and figures are baked at a handful of heights because they are drawn as
// SVG: the stroke width is set per size, so a mark comes out the same weight at
// 24 dots and at 72. These are raster drawings, so there is no stroke width to
// set — and the box they go in is not a size anybody chose. It is the blank in
// whichever pose the walker is drawn at, measured off the baked dots, and it
// came back 28x14 at the smallest figure and 45x23 at the largest. Baking a
// ladder of sizes and picking the nearest would leave dots unused at every rung,
// and on a sign 26 dots wide the dots are the whole message.
//
// So one bitmap each, at a resolution the largest blank still oversamples by
// three, scaled to the exact box when it is drawn. See signScaled, which caches
// per size — a sign holds still for the three seconds it is on screen.
//
// # Why the drawing is trimmed to its ink
//
// Two sheets were drawn for this, one plain and one with the sketched motion
// lines the characters have. The lines lost: they carry no meaning and they do
// carry bounding box. On the crossed-out loop they took the drawing from 244x163
// to 265x215, so the symbol itself got 25 dots of the 43 it could have had, and
// what reached the screen was a smudge. Trimming is what makes the box the
// symbol's rather than the page's.
package main

import (
	"encoding/base64"
	"fmt"
	"go/format"
	"image"
	_ "image/png"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// signSource is how wide a baked drawing is kept, in pixels.
//
// 160. The largest blank measured is 45 dots across, so this oversamples it by
// more than three and the small end by six — enough that scaling down never has
// to guess. Keeping the drawings at the size they were cut at would work too and
// cost four times the bytes for a difference no screen can show.
const signSource = 160

// lit is how dark a pixel has to be to count as ink, matching cmd/spindle-sheet.
const lit = 128

func main() {
	paths, err := filepath.Glob("assets/signs/*.png")
	if err != nil || len(paths) == 0 {
		panic(fmt.Sprintf("no signs in assets/signs: %v", err))
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("// Code generated by cmd/spindle-signs. DO NOT EDIT.\n\n")
	b.WriteString("package ui\n\n")
	b.WriteString("// What the walker's placard says, drawn rather than set from a face.\n")
	b.WriteString("// See cmd/spindle-signs.\n\n")
	b.WriteString("var signDrawings = map[string]signDrawing{\n")

	for _, path := range paths {
		name := strings.TrimSuffix(filepath.Base(path), ".png")
		w, h, bits := bake(path)
		fmt.Fprintf(&b, "\t%q: {wide: %d, tall: %d, bits: %q},\n", name, w, h, bits)
		fmt.Printf("  %-12s %3dx%-3d\n", name, w, h)
	}
	b.WriteString("}\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("internal/ui/signs_gen.go", out, 0o644); err != nil {
		panic(err)
	}
}

// bake reads a drawing, trims it to its ink, scales it to signSource across and
// returns the dots packed a bit to a pixel.
func bake(path string) (int, int, string) {
	f, err := os.Open(path)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		panic(err)
	}

	r := img.Bounds()
	w, h := r.Dx(), r.Dy()
	dark := func(x, y int) bool {
		cr, cg, cb, a := img.At(r.Min.X+x, r.Min.Y+y).RGBA()
		return a > 0x8000 && (cr+cg+cb)/3 < lit<<8
	}

	// The corner decides which way round it is, the same rule cmd/spindle-sheet
	// cuts by — and it has to, because that is what wrote these: it thresholds to
	// white ink on black, while the sheet it cut from was black on white. Read
	// the wrong way the ink is the paper, and every sign bakes to a solid block.
	// Which is exactly what the first bake produced.
	paper := dark(0, 0)
	ink := func(x, y int) bool { return dark(x, y) != paper }

	// Trimmed to its own ink, so the box the sign is scaled into belongs to the
	// symbol rather than to whatever margin the page had.
	x0, y0, x1, y1 := w, h, -1, -1
	for y := range h {
		for x := range w {
			if ink(x, y) {
				x0, y0 = min(x0, x), min(y0, y)
				x1, y1 = max(x1, x), max(y1, y)
			}
		}
	}
	if x1 < x0 {
		panic(path + ": no ink")
	}
	sw, sh := x1-x0+1, y1-y0+1

	dw := min(signSource, sw)
	dh := max(sh*dw/sw, 1)

	// Any ink in the patch lights the dot. A stroke three pixels wide across a
	// drawing 250 wide is gone under an average and kept under this, and every
	// one of these drawings is nothing but strokes.
	bits := make([]byte, (dw*dh+7)/8)
	for y := range dh {
		for x := range dw {
			px0, px1 := x0+x*sw/dw, x0+(x+1)*sw/dw
			py0, py1 := y0+y*sh/dh, y0+(y+1)*sh/dh
		patch:
			for py := py0; py < max(py1, py0+1); py++ {
				for px := px0; px < max(px1, px0+1); px++ {
					if ink(px, py) {
						i := y*dw + x
						bits[i/8] |= 1 << (i % 8)
						break patch
					}
				}
			}
		}
	}
	return dw, dh, base64.StdEncoding.EncodeToString(bits)
}
