// Command spindle-figures turns drawings into dots.
//
// A figure on the big screen is a small line drawing that walks about, and the
// drawing does not come from code — it comes from a picture somebody drew,
// under a licence that lets us use it. This converts one into the only thing a
// terminal can show: dots that are on or off.
//
// Run it when a figure is added or its manifest changes:
//
//	go run ./cmd/spindle-figures
//
// It reads every assets/figures/*/figure.json and writes one generated Go file
// into internal/ui. Nothing here runs at playback time; what ships is the dots.
//
// # Why edges and not the shape
//
// A filled silhouette is the obvious thing and it is wrong. Every other picture
// on that screen is a stroke two or three dots wide — the type, the meters, the
// water — and a solid figure among them reads as a hole punched in the picture.
// Worse, it throws away the face: these drawings carry their features in flat
// colour rather than in an outline, so the silhouette of a head is an egg.
//
// So what is kept is every edge: the rim of the figure, and every place inside
// it where the brightness changes by more than the manifest's gate. That comes
// out as a line drawing with the visor, the panels and the limbs in it.
package main

import (
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"image"
	"image/png"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/image/draw"
)

// figure is a manifest: where the drawings are and how to take them apart.
type figure struct {
	// Fill takes the drawing as a silhouette rather than as an outline: every
	// dot darker than Gate is set. See convert.
	Fill bool `json:"fill"`

	Name    string            `json:"name"`
	From    string            `json:"from"`
	Licence string            `json:"licence"`
	Gate    float64           `json:"gate"`
	Head    float64           `json:"head"`
	Face    float64           `json:"face"`
	Bob     int               `json:"bob"`
	Faces   string            `json:"faces"`
	Heights []height          `json:"heights"`
	Poses   map[string]string `json:"poses"`
}

// faces is which way a drawing looks: -1 left, 1 right, and 0 for a figure
// drawn front on, which is what a manifest that does not say means.
func (f figure) faces() (int, error) {
	switch f.Faces {
	case "", "front":
		return 0, nil
	case "left":
		return -1, nil
	case "right":
		return 1, nil
	}
	return 0, fmt.Errorf("%s: faces is %q, want left, right or front", f.Name, f.Faces)
}

type height struct {
	Tall  int `json:"tall"`
	Thick int `json:"thick"`
}

// pose is one drawing, converted.
type pose struct {
	name       string
	wide, tall int
	bits       string

	// head is where the face goes: the box the figure's own head fills, which
	// is found rather than given, so a head that bobs through a walk cycle is
	// followed by whatever is drawn into it.
	headX, headY, headW, headH int
}

const (
	assets = "assets/figures"
	out    = "internal/ui/figures_gen.go"
)

func main() {
	show := flag.String("show", "", "after baking, draw these figures in the terminal — a name, several separated by commas, or \"all\"")
	pose := flag.String("pose", "idle", "with -show, which pose to draw")
	only := flag.Int("size", 0, "with -show, draw only this baked height in dots")
	flag.Parse()

	dirs, err := filepath.Glob(filepath.Join(assets, "*", "figure.json"))
	if err != nil || len(dirs) == 0 {
		fail(fmt.Errorf("no figures under %s", assets))
	}
	sort.Strings(dirs)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/spindle-figures. DO NOT EDIT.\n\npackage ui\n\n")
	fmt.Fprintf(&b, "// The figures, drawn by somebody else and taken apart by the generator.\n")
	fmt.Fprintf(&b, "// See cmd/spindle-figures, and the licence beside each figure's drawings.\n\n")
	fmt.Fprintf(&b, "var figures = map[string]figureDrawing{\n")

	for _, path := range dirs {
		f, err := read(path)
		if err != nil {
			fail(err)
		}
		if err := emit(&b, filepath.Dir(path), f); err != nil {
			fail(err)
		}
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fail(fmt.Errorf("format: %w", err))
	}
	if err := os.WriteFile(out, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", out, len(src))

	if *show != "" {
		look(dirs, *show, *pose, *only)
	}
}

func read(path string) (figure, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return figure{}, err
	}
	var f figure
	if err := json.Unmarshal(raw, &f); err != nil {
		return figure{}, fmt.Errorf("%s: %w", path, err)
	}
	if f.Name == "" || len(f.Poses) == 0 || len(f.Heights) == 0 {
		return figure{}, fmt.Errorf("%s: a figure wants a name, a pose and a height", path)
	}
	return f, nil
}

func emit(b *strings.Builder, dir string, f figure) error {
	faces, err := f.faces()
	if err != nil {
		return err
	}
	fmt.Fprintf(b, "\t%q: {\n\t\tfrom: %q,\n\t\tlicence: %q,\n\t\tbob: %d,\n\t\tfaces: %d,\n\t\tsizes: []figureSize{\n",
		f.Name, f.From, f.Licence, f.Bob, faces)

	for _, h := range f.Heights {
		names := make([]string, 0, len(f.Poses))
		for name := range f.Poses {
			names = append(names, name)
		}
		sort.Strings(names)

		fmt.Fprintf(b, "\t\t\t{tall: %d, poses: map[string]figurePose{\n", h.Tall)
		for _, name := range names {
			p, err := convert(filepath.Join(dir, f.Poses[name]), name, h, f)
			if err != nil {
				return err
			}
			fmt.Fprintf(b, "\t\t\t\t%q: {wide: %d, tall: %d, headX: %d, headY: %d, headW: %d, headH: %d, bits: %q},\n",
				name, p.wide, p.tall, p.headX, p.headY, p.headW, p.headH, p.bits)
		}
		fmt.Fprintf(b, "\t\t\t}},\n")
	}
	fmt.Fprintf(b, "\t\t},\n\t},\n")
	return nil
}

// convert takes one drawing to dots at one height.
func convert(path, name string, h height, f figure) (pose, error) {
	file, err := os.Open(path)
	if err != nil {
		return pose{}, err
	}
	defer file.Close() //nolint:errcheck // reading only

	src, err := png.Decode(file)
	if err != nil {
		return pose{}, fmt.Errorf("%s: %w", path, err)
	}

	// Scaled first, then the edges found, so the stroke comes out the weight it
	// was asked for rather than whatever a full size outline shrank to.
	box := src.Bounds()
	wide := box.Dx() * h.Tall / box.Dy()
	scaled := image.NewRGBA(image.Rect(0, 0, wide, h.Tall))
	draw.CatmullRom.Scale(scaled, scaled.Bounds(), src, box, draw.Src, nil)

	gate := uint32(f.Gate * 0xffff)

	// Which way round the drawing is, asked of its corners rather than written
	// down: a silhouette arrives black on white from one hand and white on black
	// from another, and filled the wrong way round a figure comes back as the
	// hole it was cut from.
	var bright int
	for _, c := range [][2]int{{0, 0}, {wide - 1, 0}, {0, h.Tall - 1}, {wide - 1, h.Tall - 1}} {
		r, g, bl, _ := scaled.At(c[0], c[1]).RGBA()
		if (299*r+587*g+114*bl)/1000 >= 0x7fff {
			bright++
		}
	}
	dark := bright < 3
	at := func(x, y int) (uint32, uint32) {
		if x < 0 || y < 0 || x >= wide || y >= h.Tall {
			return 0, 0
		}
		r, g, bl, a := scaled.At(x, y).RGBA()
		return (299*r + 587*g + 114*bl) / 1000, a
	}

	lit := make([][]bool, h.Tall)
	for y := range lit {
		lit[y] = make([]bool, wide)
	}

	// A shadow is not an outline. Where a figure is a solid silhouette — a
	// puppet cut out of leather, a paper cut, anything whose whole shape is the
	// drawing — the edges are the wrong question: run over one, a picture with
	// any texture inside it comes back as an outline of every speck. Filled, it
	// comes back as what it is.
	//
	// Which is also the one thing on this screen that may be solid. Everything
	// else is a stroke among strokes and a filled shape reads as a hole punched
	// in the picture; a figure who walks on is not among anything.
	for y := range h.Tall {
		for x := range wide {
			lum, a := at(x, y)
			if a < 0x7fff {
				continue
			}
			if f.Fill {
				if dark && lum >= gate || !dark && lum < gate {
					lit[y][x] = true
				}
				continue
			}

			var edge bool
			for _, d := range [][2]int{{1, 0}, {0, 1}, {-1, 0}, {0, -1}} {
				near, alpha := at(x+d[0], y+d[1])
				if alpha < 0x7fff || lum > near && lum-near > gate || near > lum && near-lum > gate {
					edge = true
					break
				}
			}
			if !edge {
				continue
			}
			for dy := range h.Thick {
				for dx := range h.Thick {
					if y+dy < h.Tall && x+dx < wide {
						lit[y+dy][x+dx] = true
					}
				}
			}
		}
	}

	p := pose{name: name, wide: wide, tall: h.Tall}

	// Where the head is, and inside it where the face goes: the drawing's own
	// helmet, visor and jaw are kept, and only what they enclose is cleared.
	// The rim has to survive — it is the head.
	hx, hy, hw, hh := head(scaled, wide, h.Tall, f.Head)
	if share := f.Face; hw > 0 && hh > 0 && share > 0 && share <= 1 {
		p.headW, p.headH = int(float64(hw)*share), int(float64(hh)*share)
		p.headX, p.headY = hx+(hw-p.headW)/2, hy+(hh-p.headH)/2

		for y := p.headY; y < p.headY+p.headH; y++ {
			for x := p.headX; x < p.headX+p.headW; x++ {
				lit[y][x] = false
			}
		}
	}

	// Packed a dot to a bit and written as base64: a drawing spelled out one
	// character a dot is six times the source, and six figures of it is a
	// megabyte of Go nobody will ever read.
	stride := (wide + 7) / 8
	packed := make([]byte, stride*h.Tall)
	for y, row := range lit {
		for x, on := range row {
			if on {
				packed[y*stride+x/8] |= 1 << (x % 8)
			}
		}
	}
	p.bits = base64.StdEncoding.EncodeToString(packed)
	return p, nil
}

// head finds the figure's head: the box its own dots fill in the top share of
// it. Found rather than given, so a head that bobs through a walk cycle takes
// whatever is drawn into it along.
func head(img *image.RGBA, wide, tall int, share float64) (int, int, int, int) {
	if share <= 0 {
		return 0, 0, 0, 0
	}
	deep := int(share * float64(tall))

	left, right, top, bottom := wide, -1, tall, -1
	for y := range deep {
		for x := range wide {
			if _, _, _, a := img.At(x, y).RGBA(); a < 0x7fff {
				continue
			}
			left, right = min(left, x), max(right, x)
			top, bottom = min(top, y), max(bottom, y)
		}
	}
	if right < 0 {
		return 0, 0, 0, 0
	}
	return left, top, right - left + 1, bottom - top + 1
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "spindle-figures:", err)
	os.Exit(1)
}

// draw prints a figure in the terminal, in the dots it will be drawn in.
//
// The same reason the marks have it: a drawing is judged at the size it is seen
// at, and a figure that reads beautifully at a thousand pixels can be a smudge
// at a hundred and thirty dots. Braille, because that is what the screen draws
// in — two dots across and four down to a cell.
func look(dirs []string, want, poseName string, only int) {
	var found bool
	for _, path := range dirs {
		f, err := read(path)
		if err != nil {
			fail(err)
		}
		if want != "all" && !wanted(want, f.Name) {
			continue
		}
		found = true
		for _, h := range f.Heights {
			if only > 0 && h.Tall != only {
				continue
			}
			p, err := convert(filepath.Join(filepath.Dir(path), poseName+".png"), poseName, h, f)
			if err != nil {
				fmt.Fprintf(os.Stderr, "%s at %d: %v\n", f.Name, h.Tall, err)
				continue
			}
			fmt.Printf("\n%s %s at %d dots, pen %d — %dx%d\n", f.Name, poseName, h.Tall, h.Thick, p.wide, p.tall)
			for _, line := range braille(p) {
				fmt.Println(line)
			}
		}
	}
	if !found {
		fmt.Fprintf(os.Stderr, "spindle-figures: no figure called %q\n", want)
		os.Exit(1)
	}
}

func wanted(want, name string) bool {
	for _, one := range strings.Split(want, ",") {
		if strings.TrimSpace(one) == name {
			return true
		}
	}
	return false
}

// braille lays one pose out in braille cells.
func braille(p pose) []string {
	raw, err := base64.StdEncoding.DecodeString(p.bits)
	if err != nil {
		fail(err)
	}
	// Packed a row at a time with a stride, which is how the interface reads it
	// back — see figurePose.draw. Read as one long run of bits instead, a figure
	// comes out as diagonal noise, and it took two wrong conclusions about the
	// drawings before the reading was doubted.
	stride := (p.wide + 7) / 8
	on := func(x, y int) bool {
		if x < 0 || y < 0 || x >= p.wide || y >= p.tall {
			return false
		}
		at := y*stride + x/8
		return at < len(raw) && raw[at]&(1<<(x%8)) != 0
	}
	bit := [2][4]uint8{{0, 1, 2, 6}, {3, 4, 5, 7}}
	out := make([]string, (p.tall+3)/4)
	for r := range out {
		var b strings.Builder
		for x := 0; x < p.wide; x += 2 {
			var cell rune
			for dx := range 2 {
				for dy := range 4 {
					if on(x+dx, r*4+dy) {
						cell |= 1 << bit[dx][dy]
					}
				}
			}
			b.WriteRune(0x2800 + cell)
		}
		out[r] = b.String()
	}
	return out
}
