// Command spindle-moves turns a sheet of dance frames into dots.
//
// A figure that dances to the record needs moves rather than poses: a move is
// dealt, held for as long as the phrase lasts, and joined to the next without a
// cut. The drawings come from outside this repository — see docs/MOVES.md for
// what to ask for — as one sheet a move, laid out on an even grid.
//
// Run it when a move set is added or its manifest changes:
//
//	go run ./cmd/spindle-moves
//	go run ./cmd/spindle-moves -report
//
// It reads every assets/moves/*/move.json and writes one generated Go file into
// internal/ui. Nothing here runs at playback time; what ships is the dots.
//
// # The floor, which is the whole of the difficulty
//
// A sheet does not come back with its frames on one floor. Measured on the
// seven that started this: within a row of cells the ground is the same to
// within four pixels, and between the rows of the sheet it walks upwards by as
// much as 112 — a third of a cell. Cut on the grid and played, the figure jumps
// a third of his own height every four frames and drops back.
//
// It is an artefact of how the sheet was laid out rather than anything drawn:
// movement would vary frame by frame, and this steps once a row. So every frame
// is sat on its own lowest ink instead. That is the floor in every pose these
// moves have — feet, palms, a shoulder, the top of the head — and it holds
// wherever the figure has a part of himself on the ground, which is every frame
// of breakdancing.
//
// Sideways is left as drawn. There the measured spread is mostly real: a leg
// thrown out to the side moves the ink's middle without the body going
// anywhere, and correcting it would put in a movement rather than take one out.
package main

import (
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"image"
	"image/png"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/image/draw"
)

const (
	assets = "assets/moves"
	out    = "internal/ui/moves_gen.go"
)

// set is a manifest: where the sheets are, how they are cut, and which frames of
// each are the part that repeats.
type set struct {
	Name    string `json:"name"`
	From    string `json:"from"`
	Licence string `json:"licence"`

	// Cols and Rows are the grid every sheet is cut on. Given rather than found:
	// a sheet cannot be trusted to say, and a grid guessed wrong takes an arm
	// off every frame in the same place, which looks like a drawing.
	Cols int `json:"cols"`
	Rows int `json:"rows"`

	// Gate is how dark a pixel has to be to count as ink, and Thick how many
	// dots a stroke is drawn to at the smaller sizes.
	Gate  float64 `json:"gate"`
	Thick int     `json:"thick"`

	// Heights are what the standing pose is baked to, in dots. Everything else
	// on a sheet is scaled by whatever that took, so a move that lies flat is
	// flat rather than stretched to the same height as a move that stands.
	Heights []int  `json:"heights"`
	Moves   []move `json:"moves"`
}

// move is one sheet: a dance from standing back to standing.
type move struct {
	Name string `json:"name"`
	File string `json:"file"`

	// In, Loop and Out are frame ranges, both ends inclusive. The loop is the
	// part that may be repeated: its last frame has to lead back into its first,
	// which is what lets a move last as long as the music wants it to.
	In   [2]int `json:"in"`
	Loop [2]int `json:"loop"`
	Out  [2]int `json:"out"`
}

// frame is one drawing, cut from the sheet and converted.
//
// x is where it stands across the cell and h how tall it is; there is no y,
// because every frame sits on the floor by construction.
type frame struct {
	x, w, h int
	bits    string
	lit     []bool // kept for the report, not emitted
}

func main() {
	report := flag.Bool("report", false, "measure how well each loop joins, and how big the baked set is")
	find := flag.Bool("find", false, "look for the loop that joins best, rather than trusting the manifest")
	show := flag.String("show", "", "after baking, draw this move in the terminal")
	flag.Parse()

	found, err := filepath.Glob(filepath.Join(assets, "*", "move.json"))
	if err != nil || len(found) == 0 {
		fail(fmt.Errorf("no move sets under %s", assets))
	}
	sort.Strings(found)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/spindle-moves. DO NOT EDIT.\n\npackage ui\n\n")
	fmt.Fprintf(&b, "// The dances, drawn outside this repository and taken apart by the generator.\n")
	fmt.Fprintf(&b, "// See cmd/spindle-moves, docs/MOVES.md, and the licence beside each set.\n\n")
	fmt.Fprintf(&b, "var moveSets = map[string]moveSet{\n")

	for _, path := range found {
		s, err := read(path)
		if err != nil {
			fail(err)
		}
		if err := emit(&b, filepath.Dir(path), s, *report, *find); err != nil {
			fail(err)
		}
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fail(fmt.Errorf("format: %w", err))
	}
	if err := os.WriteFile(out, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", out, len(src))

	if *show != "" {
		for _, path := range found {
			s, err := read(path)
			if err != nil {
				fail(err)
			}
			if err := showMove(filepath.Dir(path), s, *show); err == nil {
				return
			}
		}
		fail(fmt.Errorf("no move called %q", *show))
	}
}

func read(path string) (set, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return set{}, err
	}
	var s set
	if err := json.Unmarshal(raw, &s); err != nil {
		return set{}, fmt.Errorf("%s: %w", path, err)
	}
	switch {
	case s.Name == "":
		return set{}, fmt.Errorf("%s: a set wants a name", path)
	case s.Cols <= 0 || s.Rows <= 0:
		return set{}, fmt.Errorf("%s: a set wants the grid its sheets are cut on", path)
	case len(s.Moves) == 0 || len(s.Heights) == 0:
		return set{}, fmt.Errorf("%s: a set wants a move and a height", path)
	}
	if s.Thick < 1 {
		s.Thick = 1
	}
	return s, nil
}

func emit(b *strings.Builder, dir string, s set, report, find bool) error {
	fmt.Fprintf(b, "\t%q: {\n\t\tfrom: %q,\n\t\tlicence: %q,\n\t\tsizes: []moveSize{\n", s.Name, s.From, s.Licence)

	for _, tall := range s.Heights {
		type baked struct {
			m      move
			frames []frame
			cell   int
		}
		var all []baked
		var wide int

		for _, mv := range s.Moves {
			frames, cellWide, err := cut(filepath.Join(dir, mv.File), s, tall)
			if err != nil {
				return fmt.Errorf("%s: %w", mv.Name, err)
			}
			wide = max(wide, cellWide)
			all = append(all, baked{mv, frames, cellWide})
			if report {
				say(s.Name, tall, mv, frames)
			}
			if find && tall == s.Heights[0] {
				look(mv, frames)
			}
		}

		// Each sheet is scaled by what its own standing pose took, so their cells
		// come out a dot or two apart. They all stand in the widest of them,
		// centred, or a frame measured in one cell would be placed in another.
		for _, one := range all {
			for i := range one.frames {
				one.frames[i].x += (wide - one.cell) / 2
			}
		}

		fmt.Fprintf(b, "\t\t\t{tall: %d, wide: %d, moves: map[string]moveDance{\n", tall, wide)
		for _, one := range all {
			fmt.Fprintf(b, "\t\t\t\t%q: {inFrom: %d, inTo: %d, loopFrom: %d, loopTo: %d, outFrom: %d, outTo: %d, frames: []moveFrame{\n",
				one.m.Name, one.m.In[0], one.m.In[1], one.m.Loop[0], one.m.Loop[1], one.m.Out[0], one.m.Out[1])
			for _, f := range one.frames {
				fmt.Fprintf(b, "\t\t\t\t\t{x: %d, wide: %d, tall: %d, bits: %q},\n", f.x, f.w, f.h, f.bits)
			}
			fmt.Fprintf(b, "\t\t\t\t}},\n")
		}
		fmt.Fprintf(b, "\t\t\t}},\n")
	}
	fmt.Fprintf(b, "\t\t},\n\t},\n")
	return nil
}

// cut takes one sheet to dots at one height, and reports how wide a cell came
// out — every frame of the set stands in a cell that size.
func cut(path string, s set, tall int) ([]frame, int, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, 0, err
	}
	defer file.Close() //nolint:errcheck // reading only

	src, err := png.Decode(file)
	if err != nil {
		return nil, 0, fmt.Errorf("%s: %w", path, err)
	}

	box := src.Bounds()
	cw, ch := box.Dx()/s.Cols, box.Dy()/s.Rows
	gate := uint32(s.Gate * 0xffff)

	// Which way round the sheet is, asked of its corners: black on white from
	// one hand and white on black from another, and taken the wrong way round a
	// figure comes back as the hole he was cut from.
	dark := lightCorners(src, gate) >= 3

	ink := func(x, y int) bool {
		r, g, bl, a := src.At(box.Min.X+x, box.Min.Y+y).RGBA()
		if a < 0x7fff {
			return false
		}
		lum := (299*r + 587*g + 114*bl) / 1000
		if dark {
			return lum < gate
		}
		return lum >= gate
	}

	// The standing pose is the first cell, and it is what sets the scale for the
	// whole sheet: everything else is scaled by whatever it took, so a move that
	// lies flat comes out flat.
	stand, ok := inkBox(ink, 0, 0, cw, ch)
	if !ok {
		return nil, 0, fmt.Errorf("%s: the first cell is empty, so there is no standing pose to measure", path)
	}
	// What it takes to make the standing pose exactly as tall as it was asked
	// for. Once is not enough: an outline resampled loses the faintest row of
	// its own edge, so the first attempt lands a dot short and the correction
	// puts it back. Measured rather than fudged — the height of the standing
	// pose is what every other frame of the sheet is scaled by.
	scale := float64(tall) / float64(stand.Dy())
	for range 4 {
		got, ok := standing(src, box, cw, ch, scale, dark, gate)
		if !ok || got == tall {
			break
		}
		scale *= float64(tall) / float64(got)
	}
	cellWide, cellTall := int(float64(cw)*scale), int(float64(ch)*scale)

	var out []frame
	for i := range s.Cols * s.Rows {
		x0, y0 := (i%s.Cols)*cw, (i/s.Cols)*ch

		// Scaled as a whole cell rather than as its own ink, so that where the
		// figure stands across the cell survives. Only then is the ink found:
		// the stroke comes out the weight it is drawn at this size, rather than
		// whatever a full-size outline shrank to.
		cell := image.NewRGBA(image.Rect(0, 0, cellWide, cellTall))
		draw.CatmullRom.Scale(cell, cell.Bounds(),
			src, image.Rect(box.Min.X+x0, box.Min.Y+y0, box.Min.X+x0+cw, box.Min.Y+y0+ch), draw.Src, nil)

		hot := func(x, y int) bool {
			if x < 0 || y < 0 || x >= cellWide || y >= cellTall {
				return false
			}
			r, g, bl, a := cell.At(x, y).RGBA()
			if a < 0x7fff {
				return false
			}
			lum := (299*r + 587*g + 114*bl) / 1000
			if dark {
				return lum < gate
			}
			return lum >= gate
		}
		at, ok := inkBox(hot, 0, 0, cellWide, cellTall)
		if !ok {
			return nil, 0, fmt.Errorf("%s: cell %d is empty", path, i)
		}

		f := frame{x: at.Min.X, w: at.Dx(), h: at.Dy()}
		f.lit = make([]bool, f.w*f.h)
		for y := range f.h {
			for x := range f.w {
				if !hot(at.Min.X+x, at.Min.Y+y) {
					continue
				}
				for dy := range s.Thick {
					for dx := range s.Thick {
						if y+dy < f.h && x+dx < f.w {
							f.lit[(y+dy)*f.w+x+dx] = true
						}
					}
				}
			}
		}

		// Packed a dot to a bit and written as base64: spelled out a character
		// a dot, one sheet is a megabyte of Go nobody will ever read.
		stride := (f.w + 7) / 8
		packed := make([]byte, stride*f.h)
		for y := range f.h {
			for x := range f.w {
				if f.lit[y*f.w+x] {
					packed[y*stride+x/8] |= 1 << (x % 8)
				}
			}
		}
		f.bits = base64.StdEncoding.EncodeToString(packed)
		out = append(out, f)
	}
	return out, cellWide, nil
}

// inkBox is the box the ink fills inside a region, and whether there was any.
func inkBox(ink func(x, y int) bool, x0, y0, w, h int) (image.Rectangle, bool) {
	minX, minY, maxX, maxY := w, h, -1, -1
	for y := range h {
		for x := range w {
			if !ink(x0+x, y0+y) {
				continue
			}
			minX, maxX = min(minX, x), max(maxX, x)
			minY, maxY = min(minY, y), max(maxY, y)
		}
	}
	if maxY < 0 {
		return image.Rectangle{}, false
	}
	return image.Rect(minX, minY, maxX+1, maxY+1), true
}

func lightCorners(src image.Image, gate uint32) int {
	b := src.Bounds()
	var light int
	for _, c := range [][2]int{
		{b.Min.X, b.Min.Y}, {b.Max.X - 1, b.Min.Y},
		{b.Min.X, b.Max.Y - 1}, {b.Max.X - 1, b.Max.Y - 1},
	} {
		r, g, bl, _ := src.At(c[0], c[1]).RGBA()
		if (299*r+587*g+114*bl)/1000 >= gate {
			light++
		}
	}
	return light
}

// say measures what was baked: how big it is, and — the number the manifest is
// really asking about — how well the loop joins.
//
// A loop is only a loop if its last frame leads back into its first. That is
// measurable: count the dots that change across the join and compare them with
// what changes at an ordinary step inside the loop. A join that costs about what
// a step costs is a join nobody will see; one that costs three times as much is
// a jump, and the frame numbers in the manifest are wrong.
func say(setName string, tall int, mv move, frames []frame) {
	var bytes int
	for _, f := range frames {
		bytes += len(f.bits)
	}

	from, to := mv.Loop[0], mv.Loop[1]
	if from < 0 || to >= len(frames) || to <= from {
		fmt.Printf("  %-10s %3d dots  %2d frames  %5.1f kB  (no loop given)\n",
			mv.Name, tall, len(frames), float64(bytes)/1024)
		return
	}

	var steps int
	for i := from; i < to; i++ {
		steps += changed(frames[i], frames[i+1])
	}
	step := float64(steps) / float64(to-from)
	join := float64(changed(frames[to], frames[from]))

	flag := ""
	if join > 2*step {
		flag = "  <-- the loop jumps"
	}
	fmt.Printf("  %-10s %3d dots  %2d frames  %5.1f kB  step %5.0f dots, join %5.0f (%.1fx)%s\n",
		mv.Name, tall, len(frames), float64(bytes)/1024, step, join, join/step, flag)
}

// changed is how many dots differ between two frames, laid over each other the
// way they are drawn: on the same floor, at the place each stands across the
// cell.
func changed(a, b frame) int {
	minX := min(a.x, b.x)
	wide := max(a.x+a.w, b.x+b.w) - minX
	tall := max(a.h, b.h)

	on := func(f frame, x, y int) bool {
		// Measured up from the floor, which is where both of them sit.
		fx, fy := x-(f.x-minX), y-(tall-f.h)
		if fx < 0 || fy < 0 || fx >= f.w || fy >= f.h {
			return false
		}
		return f.lit[fy*f.w+fx]
	}

	var n int
	for y := range tall {
		for x := range wide {
			if on(a, x, y) != on(b, x, y) {
				n++
			}
		}
	}
	return n
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "spindle-moves:", err)
	os.Exit(1)
}

// look asks the frames themselves whether the loop is where the manifest says.
//
// Of every stretch the same length as the one given, the one whose end leads
// back into its beginning most cheaply. The same length on purpose: allowed to
// choose its own, the search always answers with the shortest stretch of the
// most similar frames — on the standing bounce it offered eight frames out of
// nineteen, which is not a better loop but half a dance.
func look(mv move, frames []frame) {
	span := mv.Loop[1] - mv.Loop[0]
	if span < 2 {
		return
	}

	// Never over the standing pose at either end: a loop that repeats it is a
	// dance that stands still once a bar. The bounce is the exception and says
	// so by looping the whole sheet.
	first, last := 1, len(frames)-2
	if mv.Loop[0] == 0 {
		first, last = 0, len(frames)-1
	}

	best, bestAt := -1, 0.0
	for from := first; from+span <= last; from++ {
		if at := joins(frames, from, from+span); best < 0 || at < bestAt {
			best, bestAt = from, at
		}
	}
	fmt.Printf("  %-10s loop %2d-%2d joins at %.2fx  ·  best %d frames elsewhere: %d-%d at %.2fx\n",
		mv.Name, mv.Loop[0], mv.Loop[1], joins(frames, mv.Loop[0], mv.Loop[1]),
		span+1, best, best+span, bestAt)
}

// joins is what the loop's own join costs against what a step inside it costs.
// One is a join nobody sees; three is a jump.
func joins(frames []frame, from, to int) float64 {
	var steps int
	for i := from; i < to; i++ {
		steps += changed(frames[i], frames[i+1])
	}
	step := float64(steps) / float64(to-from)
	if step == 0 {
		return 0
	}
	return float64(changed(frames[to], frames[from])) / step
}

// showMove draws a move's frames in the terminal, in braille, at the smallest
// baked height.
//
// Because the fault this tool exists to fix is invisible in the numbers. The
// floor is either under him in every frame or it is not, and the only way to
// know is to look at twenty frames standing on one line — which is exactly what
// this prints.
func showMove(dir string, s set, name string) error {
	var mv move
	for _, one := range s.Moves {
		if one.Name == name {
			mv = one
		}
	}
	if mv.File == "" {
		return fmt.Errorf("no move called %q in %s", name, s.Name)
	}

	tall := s.Heights[0]
	frames, wide, err := cut(filepath.Join(dir, mv.File), s, tall)
	if err != nil {
		return err
	}

	const across = 5
	for at := 0; at < len(frames); at += across {
		end := min(at+across, len(frames))
		row := frames[at:end]

		// One canvas for the row, so they stand on one floor and the eye can
		// see whether they do.
		w := (wide + 2) * len(row)
		lit := make([]bool, w*tall)
		for i, f := range row {
			for y := range f.h {
				for x := range f.w {
					if !f.lit[y*f.w+x] {
						continue
					}
					// Up from the floor: the frame's bottom is the ground.
					px, py := i*(wide+2)+f.x+x, tall-f.h+y
					if px >= 0 && px < w && py >= 0 && py < tall {
						lit[py*w+px] = true
					}
				}
			}
		}

		fmt.Printf("\n  frames %d-%d\n", at, end-1)
		for y := 0; y < tall; y += 4 {
			var line strings.Builder
			for x := 0; x < w; x += 2 {
				var bits rune
				for _, d := range [][3]int{{0, 0, 0}, {0, 1, 1}, {0, 2, 2}, {1, 0, 3}, {1, 1, 4}, {1, 2, 5}, {0, 3, 6}, {1, 3, 7}} {
					if px, py := x+d[0], y+d[1]; px < w && py < tall && lit[py*w+px] {
						bits |= 1 << d[2]
					}
				}
				line.WriteRune(0x2800 + bits)
			}
			fmt.Println("  " + line.String())
		}
	}
	return nil
}

// standing is how tall the standing pose comes out at a given scale, which is
// what the scale is being chosen to get right.
func standing(src image.Image, box image.Rectangle, cw, ch int, scale float64, dark bool, gate uint32) (int, bool) {
	wide, tall := int(float64(cw)*scale), int(float64(ch)*scale)
	if wide <= 0 || tall <= 0 {
		return 0, false
	}
	cell := image.NewRGBA(image.Rect(0, 0, wide, tall))
	draw.CatmullRom.Scale(cell, cell.Bounds(),
		src, image.Rect(box.Min.X, box.Min.Y, box.Min.X+cw, box.Min.Y+ch), draw.Src, nil)

	at, ok := inkBox(func(x, y int) bool {
		if x < 0 || y < 0 || x >= wide || y >= tall {
			return false
		}
		r, g, bl, a := cell.At(x, y).RGBA()
		if a < 0x7fff {
			return false
		}
		lum := (299*r + 587*g + 114*bl) / 1000
		if dark {
			return lum < gate
		}
		return lum >= gate
	}, 0, 0, wide, tall)
	if !ok {
		return 0, false
	}
	return at.Dy(), true
}
